# deno-fmt-ignore-file

name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        if: ${{ env.RUN_TEST != '' && env.RUN_TEST != '0' }}
        run: deno task test

  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package
        run: deno publish
